[theme]
base = "light"
primaryColor = "#315b86"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f7fa"
textColor = "#16202d"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 25

[browser]
gatherUsageStats = false
